from django.urls import path
from . import visor_views
from .views_cargas import EstadoImportacionView, CancelarImportacionView, SelectorView
from .views import (AgregarAccesoEstudioView, AnalizarImportacionView,
                    CompletarArchivoImportadoView, ConfirmarImportacionView, CrearEstudioView,
                    CrearImportacionView, DescargarEstudioCompletoView, DetalleEstudioView,
                    DetalleImportacionView, IniciarArchivoImportadoView,
                    EliminarEstudioView, IniciarImportacionView, ListaEstudiosView,
                    PurgarEstudioView,
                    RegistrarPacienteDetectadoView,
                    RevocarAccesoEstudioView, PublicarEstudioView, VerEstudioView)

urlpatterns = [
    path("<int:pk>/visor/", visor_views.pagina, name="visor_estudio"),
    path("<int:pk>/visor/catalogo/", visor_views.catalogo, name="visor_catalogo"),
    path("<int:pk>/visor/series/<str:serie_id>/", visor_views.serie, name="visor_serie"),
    path("<int:pk>/visor/archivos/<int:archivo_id>/contenido/", visor_views.contenido, name="visor_contenido"),
    path("<int:pk>/visor/eventos/", visor_views.eventos, name="visor_eventos"),
    path("selectores/pacientes/", SelectorView.as_view(), name="selector_pacientes"),
    path("selectores/odontologos/", SelectorView.as_view(tipo="odontologos"), name="selector_odontologos"),
    path("importaciones/<int:importacion_id>/estado/", EstadoImportacionView.as_view(), name="importacion_estado"),
    path("importaciones/<int:importacion_id>/cancelar/", CancelarImportacionView.as_view(), name="importacion_cancelar"),
    path("", ListaEstudiosView.as_view(), name="estudio_lista"),
    path("crear/", CrearEstudioView.as_view(), name="estudio_crear"),
    path("<int:pk>/ver/", VerEstudioView.as_view(), name="estudio_ver"),
    path("<int:pk>/descargar/", DescargarEstudioCompletoView.as_view(), name="estudio_descargar_completo"),
    path("importar/", CrearImportacionView.as_view(), name="importacion_crear"),
    path("importaciones/iniciar/", IniciarImportacionView.as_view(), name="importacion_iniciar"),
    path("importaciones/<int:importacion_id>/archivos/iniciar/", IniciarArchivoImportadoView.as_view(), name="importacion_archivo_iniciar"),
    path("importaciones/<int:importacion_id>/archivos/<int:archivo_id>/completar/", CompletarArchivoImportadoView.as_view(), name="importacion_archivo_completar"),
    path("importaciones/<int:importacion_id>/analizar/", AnalizarImportacionView.as_view(), name="importacion_analizar"),
    path("importaciones/<int:pk>/", DetalleImportacionView.as_view(), name="importacion_detalle"),
    path("importaciones/<int:importacion_id>/registrar-paciente/", RegistrarPacienteDetectadoView.as_view(), name="importacion_registrar_paciente"),
    path("importaciones/<int:importacion_id>/confirmar/", ConfirmarImportacionView.as_view(), name="importacion_confirmar"),
    path("<int:pk>/publicar/", PublicarEstudioView.as_view(), name="estudio_publicar"),
    path("<int:pk>/eliminar/", EliminarEstudioView.as_view(), name="estudio_eliminar"),
    path("<int:pk>/purgar/", PurgarEstudioView.as_view(), name="estudio_purgar"),
    path("<int:pk>/accesos/agregar/", AgregarAccesoEstudioView.as_view(), name="estudio_acceso_agregar"),
    path("<int:pk>/accesos/<int:autorizacion_id>/revocar/", RevocarAccesoEstudioView.as_view(), name="estudio_acceso_revocar"),
    path("<int:pk>/", DetalleEstudioView.as_view(), name="estudio_detalle"),
]
