# Generated by Django 6.1 on 2026-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_estudio', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('EN_REVISION', 'En revisión'), ('ELIMINADO', 'Eliminado')], default='BORRADOR', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estudio',
                'verbose_name_plural': 'estudios',
                'db_table': 'estudio',
                'ordering': ['-fecha_estudio', '-created_at'],
            },
        ),
    ]
