# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='pacientes.paciente'),
        ),
    ]
