# Generated by Django 6.1 on 2026-08-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_initial'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estudio',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['BORRADOR', 'PUBLICADO', 'EN_REVISION', 'ELIMINADO'])), name='ck_estudio_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='estudio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'PUBLICADO'), _negated=True), ('fecha_publicacion__isnull', False), _connector='OR'), name='ck_estudio_publicado_con_fecha'),
        ),
    ]
