# Generated by Django 6.1 on 2026-09-10 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0003_estudio_ck_estudio_estado_valido_and_more'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carpeta', models.CharField(max_length=255)),
                ('formato_detectado', models.CharField(choices=[('DICOM', 'DICOM'), ('GALILEOS', 'Galileos'), ('STL', 'STL'), ('RADIOGRAFIA', 'Radiografía'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=30)),
                ('software_origen', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('CARGANDO', 'Cargando'), ('PROCESANDO', 'Procesando'), ('PENDIENTE_CONFIRMACION', 'Pendiente de confirmación'), ('CONFIRMADA', 'Confirmada'), ('ERROR', 'Error'), ('CANCELADA', 'Cancelada')], default='CARGANDO', max_length=30)),
                ('nivel_confianza', models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10, null=True)),
                ('nombre_paciente_detectado', models.CharField(blank=True, max_length=200)),
                ('identificador_paciente_detectado', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento_detectada', models.DateField(blank=True, null=True)),
                ('fecha_estudio_detectada', models.DateField(blank=True, null=True)),
                ('descripcion_detectada', models.CharField(blank=True, max_length=255)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('cantidad_archivos', models.PositiveIntegerField(default=0)),
                ('tamano_total', models.PositiveBigIntegerField(default=0)),
                ('advertencias', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalizada_at', models.DateTimeField(blank=True, null=True)),
                ('estudio', models.ForeignKey(blank=True, db_column='id_estudio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='estudios.estudio')),
                ('iniciada_por', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('paciente_sugerido', models.ForeignKey(blank=True, db_column='id_paciente_sugerido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_sugeridas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'importación de estudio',
                'verbose_name_plural': 'importaciones de estudios',
                'db_table': 'importacion_estudio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerieDicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=64)),
                ('modalidad', models.CharField(blank=True, max_length=16)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('numero_serie', models.IntegerField(blank=True, null=True)),
                ('cantidad_archivos', models.PositiveIntegerField(default=0)),
                ('importacion', models.ForeignKey(db_column='id_importacion', on_delete=django.db.models.deletion.PROTECT, related_name='series_dicom', to='estudios.importacionestudio')),
            ],
            options={
                'verbose_name': 'serie DICOM',
                'verbose_name_plural': 'series DICOM',
                'db_table': 'serie_dicom',
            },
        ),
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['CARGANDO', 'PROCESANDO', 'PENDIENTE_CONFIRMACION', 'CONFIRMADA', 'ERROR', 'CANCELADA'])), name='ck_importacion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(('formato_detectado__in', ['DICOM', 'GALILEOS', 'STL', 'RADIOGRAFIA', 'DESCONOCIDO'])), name='ck_importacion_formato_valido'),
        ),
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_confianza__isnull', True), ('nivel_confianza__in', ['ALTA', 'MEDIA', 'BAJA']), _connector='OR'), name='ck_importacion_confianza_valida'),
        ),
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CONFIRMADA'), _negated=True), ('estudio__isnull', False), _connector='OR'), name='ck_importacion_confirmada_con_estudio'),
        ),
        migrations.AddConstraint(
            model_name='seriedicom',
            constraint=models.UniqueConstraint(fields=('importacion', 'series_instance_uid'), name='uq_serie_dicom_importacion_uid'),
        ),
    ]
