# Generated by Django 6.1 on 2026-09-10 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0004_importacionestudio_seriedicom_and_more'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CONFIRMADA'), _negated=True), models.Q(('formato_detectado', 'DESCONOCIDO'), _negated=True), _connector='OR'), name='ck_importacion_confirmada_con_formato'),
        ),
        migrations.AddConstraint(
            model_name='importacionestudio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CONFIRMADA'), _negated=True), ('finalizada_at__isnull', False), _connector='OR'), name='ck_importacion_confirmada_finalizada'),
        ),
    ]
