# Generated by Django 6.1 on 2026-09-10 23:14

import django.db.models.deletion
from django.db import migrations, models


def trasladar_deteccion_a_json(apps, schema_editor):
    """Preserva importaciones existentes al unificar campos detectados."""

    ImportacionEstudio = apps.get_model("estudios", "ImportacionEstudio")
    for importacion in ImportacionEstudio.objects.all().iterator():
        importacion.datos_detectados = {
            "formato": importacion.formato_detectado or "DESCONOCIDO",
            "software_origen": importacion.software_origen or "",
            "nombre_paciente": importacion.nombre_paciente_detectado or "",
            "identificador_paciente": importacion.identificador_paciente_detectado or "",
            "fecha_nacimiento": (
                importacion.fecha_nacimiento_detectada.isoformat()
                if importacion.fecha_nacimiento_detectada else ""
            ),
            "fecha_estudio": (
                importacion.fecha_estudio_detectada.isoformat()
                if importacion.fecha_estudio_detectada else ""
            ),
            "study_instance_uid": importacion.study_instance_uid or "",
            "descripcion": importacion.descripcion_detectada or "",
            "advertencias": importacion.advertencias or [],
        }
        importacion.save(update_fields=["datos_detectados"])


def no_revertir_json(apps, schema_editor):
    """Una reversión de esquema no intenta reconstruir columnas descartadas."""


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0007_simplificar_importacion_por_carpeta'),
        ('estudios', '0005_importacionestudio_ck_importacion_confirmada_con_formato_and_more'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seriedicom',
            name='uq_serie_dicom_importacion_uid',
        ),
        migrations.RemoveConstraint(
            model_name='importacionestudio',
            name='ck_importacion_formato_valido',
        ),
        migrations.RemoveConstraint(
            model_name='importacionestudio',
            name='ck_importacion_confianza_valida',
        ),
        migrations.RemoveConstraint(
            model_name='importacionestudio',
            name='ck_importacion_confirmada_con_formato',
        ),
        migrations.RemoveConstraint(
            model_name='importacionestudio',
            name='ck_importacion_confirmada_finalizada',
        ),
        migrations.AddField(
            model_name='importacionestudio',
            name='datos_detectados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importacionestudio',
            name='estudio',
            field=models.ForeignKey(blank=True, db_column='id_estudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to='estudios.estudio'),
        ),
        migrations.AlterField(
            model_name='importacionestudio',
            name='paciente_sugerido',
            field=models.ForeignKey(blank=True, db_column='id_paciente_sugerido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_sugeridas', to='pacientes.paciente'),
        ),
        migrations.RunPython(trasladar_deteccion_a_json, no_revertir_json),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='advertencias',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='descripcion_detectada',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='fecha_estudio_detectada',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='fecha_nacimiento_detectada',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='finalizada_at',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='formato_detectado',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='identificador_paciente_detectado',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='nivel_confianza',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='nombre_paciente_detectado',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='software_origen',
        ),
        migrations.RemoveField(
            model_name='importacionestudio',
            name='study_instance_uid',
        ),
        migrations.DeleteModel(
            name='SerieDicom',
        ),
    ]
