# Generated by Django 6.1 on 2026-09-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0006_simplificar_importacion_por_carpeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudios_eliminados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='motivo_eliminacion',
            field=models.TextField(blank=True),
        ),
    ]
