# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('DICOM', 'DICOM'), ('STL', 'STL'), ('PLY', 'PLY'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('TIFF', 'TIFF'), ('PDF', 'PDF'), ('GALILEOS', 'Galileos'), ('SIDEXIS', 'Sidexis'), ('OTRO', 'Otro')], max_length=50)),
                ('categoria', models.CharField(choices=[('DICOM', 'DICOM'), ('MODELO_3D', 'Modelo 3D'), ('IMAGEN_DOCUMENTO', 'Imagen o documento'), ('PAQUETE_PROPIETARIO', 'Paquete propietario')], max_length=30)),
                ('ruta_almacenamiento', models.CharField(max_length=500)),
                ('tamano', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('CARGANDO', 'Cargando'), ('COMPLETO', 'Completo'), ('INCORRECTO', 'Incorrecto'), ('REEMPLAZADO', 'Reemplazado')], default='CARGANDO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivo_reemplazado', models.ForeignKey(blank=True, db_column='id_archivo_reemplazado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='archivos.archivo')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'db_table': 'archivo',
            },
        ),
    ]
