# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0001_initial'),
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='estudio',
            field=models.ForeignKey(db_column='id_estudio', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='estudios.estudio'),
        ),
    ]
