# Generated by Django 6.1 on 2026-08-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_initial'),
        ('estudios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo_reemplazado',
            field=models.ForeignKey(blank=True, db_column='id_archivo_reemplazado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazos', to='archivos.archivo'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('formato__in', ['DICOM', 'STL', 'PLY', 'JPG', 'PNG', 'TIFF', 'PDF', 'GALILEOS', 'SIDEXIS', 'OTRO'])), name='ck_archivo_formato_valido'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('categoria__in', ['DICOM', 'MODELO_3D', 'IMAGEN_DOCUMENTO', 'PAQUETE_PROPIETARIO'])), name='ck_archivo_categoria_valida'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['CARGANDO', 'COMPLETO', 'INCORRECTO', 'REEMPLAZADO'])), name='ck_archivo_estado_valido'),
        ),
    ]
