# Generated by Django 6.1 on 2026-09-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_alter_archivo_archivo_reemplazado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='cantidad_partes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='archivo',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='archivo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='upload_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(
                condition=models.Q(('cantidad_partes__gte', 1)),
                name='ck_archivo_cantidad_partes_positiva',
            ),
        ),
    ]
