# Generated by Django 6.1 on 2026-09-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_archivo_cantidad_partes_archivo_content_type_and_more'),
        ('estudios', '0004_importacionestudio_seriedicom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='importacion',
            field=models.ForeignKey(blank=True, db_column='id_importacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='estudios.importacionestudio'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='ruta_relativa',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='archivo',
            name='ruta_relativa_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='archivo',
            name='serie_dicom',
            field=models.ForeignKey(blank=True, db_column='id_serie', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='estudios.seriedicom'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='sop_instance_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('serie_dicom__isnull', True), ('importacion__isnull', False), _connector='OR'), name='ck_archivo_serie_con_importacion'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('importacion__isnull', True), models.Q(('ruta_relativa', ''), _negated=True), _connector='OR'), name='ck_archivo_importado_con_ruta'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.UniqueConstraint(fields=('importacion', 'ruta_relativa_hash'), name='uq_archivo_importacion_ruta_hash'),
        ),
    ]
