# Generated by Django 6.1 on 2026-09-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0005_archivo_importacion_archivo_ruta_relativa_and_more'),
        ('estudios', '0005_importacionestudio_ck_importacion_confirmada_con_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='estudio',
            field=models.ForeignKey(blank=True, db_column='id_estudio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='estudios.estudio'),
        ),
    ]
