# Generated by Django 6.1 on 2026-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0006_archivo_estudio_opcional_importacion'),
        ('estudios', '0005_importacionestudio_ck_importacion_confirmada_con_formato_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archivo',
            name='ck_archivo_serie_con_importacion',
        ),
        migrations.RemoveConstraint(
            model_name='archivo',
            name='uq_archivo_importacion_ruta_hash',
        ),
        migrations.AddField(
            model_name='archivo',
            name='series_instance_uid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='ruta_relativa',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.UniqueConstraint(fields=('importacion', 'ruta_relativa'), name='uq_archivo_importacion_ruta'),
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='ruta_relativa_hash',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='serie_dicom',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='sop_instance_uid',
        ),
    ]
