# Generated by Django 6.1 on 2026-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0007_simplificar_importacion_por_carpeta'),
        ('estudios', '0007_estudio_eliminado_por_estudio_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='archivo',
            name='ck_archivo_estado_valido',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='estado',
            field=models.CharField(choices=[('CARGANDO', 'Cargando'), ('COMPLETO', 'Completo'), ('INCORRECTO', 'Incorrecto'), ('REEMPLAZADO', 'Reemplazado'), ('PURGADO', 'Purgado del almacenamiento')], default='CARGANDO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['CARGANDO', 'COMPLETO', 'INCORRECTO', 'REEMPLAZADO', 'PURGADO'])), name='ck_archivo_estado_valido'),
        ),
    ]
