# Generated by Django 6.1 on 2026-08-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='teléfono'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), models.Q(('telefono__isnull', False), models.Q(('telefono', ''), _negated=True)), _connector='OR'), name='ck_usuario_medio_contacto'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('rol__in', ['ADMINISTRADOR', 'ODONTOLOGO', 'PACIENTE'])), name='ck_usuario_rol_valido'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'HABILITADA', 'DESHABILITADA'])), name='ck_usuario_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'HABILITADA'), ('is_active', True)), models.Q(('estado__in', ['PENDIENTE', 'DESHABILITADA']), ('is_active', False)), _connector='OR'), name='ck_usuario_estado_autenticacion'),
        ),
    ]
