# Generated by Django 6.1 on 2026-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_acceso', models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOCADO', 'Revocado')], default='VIGENTE', max_length=15)),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'autorización',
                'verbose_name_plural': 'autorizaciones',
                'db_table': 'autorizacion',
            },
        ),
    ]
