# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacion',
            name='odontologo',
            field=models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='usuarios.odontologo'),
        ),
        migrations.AddField(
            model_name='autorizacion',
            name='revocado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_revocadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='autorizacion',
            constraint=models.UniqueConstraint(fields=('odontologo', 'estudio'), name='uq_autorizacion_odontologo_estudio'),
        ),
    ]
