# Generated by Django 6.1 on 2026-08-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_initial'),
        ('estudios', '0002_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacion',
            name='estudio',
            field=models.ForeignKey(db_column='id_estudio', on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='estudios.estudio'),
        ),
        migrations.AlterField(
            model_name='autorizacion',
            name='revocado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_revocadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='autorizacion',
            constraint=models.CheckConstraint(condition=models.Q(('estado_acceso__in', ['VIGENTE', 'REVOCADO'])), name='ck_autorizacion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='autorizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_acceso', 'VIGENTE'), ('fecha_revocacion__isnull', True), ('revocado_por__isnull', True)), models.Q(('estado_acceso', 'REVOCADO'), ('fecha_revocacion__isnull', False), ('revocado_por__isnull', False)), _connector='OR'), name='ck_autorizacion_datos_revocacion'),
        ),
    ]
