# Generated by Django 6.1 on 2026-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CARGA', 'Carga'), ('PUBLICACION', 'Publicación'), ('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('REVOCACION', 'Revocación'), ('CORRECCION', 'Corrección'), ('ELIMINACION', 'Eliminación')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registros de actividad',
                'db_table': 'log_actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
