# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='estudio',
            field=models.ForeignKey(blank=True, db_column='id_estudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actividad', to='estudios.estudio'),
        ),
    ]
