# Generated by Django 6.1 on 2026-08-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validar_logs_con_usuario(apps, schema_editor):
    """Detiene la migración si existen registros antiguos sin responsable."""
    LogActividad = apps.get_model('auditoria', 'LogActividad')
    if LogActividad.objects.filter(usuario__isnull=True).exists():
        raise RuntimeError(
            'Existen registros de auditoría sin usuario. '
            'Deben asociarse manualmente antes de continuar la migración.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_initial'),
        ('estudios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='tipo_evento',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('CARGA', 'Carga'), ('PUBLICACION', 'Publicación'), ('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('REVOCACION', 'Revocación'), ('CORRECCION', 'Corrección'), ('ELIMINACION', 'Eliminación'), ('NOTIFICACION', 'Notificación'), ('MODIFICACION_USUARIO', 'Modificación de usuario')], max_length=20),
        ),
        migrations.RunPython(
            validar_logs_con_usuario,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='logs_actividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='logactividad',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['INICIO_SESION', 'CARGA', 'PUBLICACION', 'VISUALIZACION', 'DESCARGA', 'REVOCACION', 'CORRECCION', 'ELIMINACION', 'NOTIFICACION', 'MODIFICACION_USUARIO'])), name='ck_log_tipo_evento_valido'),
        ),
    ]
