# Generated by Django 6.1 on 2026-09-10 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_logactividad_tipo_evento_and_more'),
        ('estudios', '0003_estudio_ck_estudio_estado_valido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logactividad',
            name='ck_log_tipo_evento_valido',
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='tipo_evento',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('CARGA', 'Carga'), ('PUBLICACION', 'Publicación'), ('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('REVOCACION', 'Revocación'), ('CORRECCION', 'Corrección'), ('ELIMINACION', 'Eliminación'), ('NOTIFICACION', 'Notificación'), ('MODIFICACION_USUARIO', 'Modificación de usuario'), ('IMPORTACION_INICIADA', 'Importación iniciada'), ('DETECCION_COMPLETADA', 'Detección completada'), ('IMPORTACION_CONFIRMADA', 'Importación confirmada'), ('IMPORTACION_CANCELADA', 'Importación cancelada'), ('ERROR_PROCESAMIENTO', 'Error de procesamiento')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='logactividad',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['INICIO_SESION', 'CARGA', 'PUBLICACION', 'VISUALIZACION', 'DESCARGA', 'REVOCACION', 'CORRECCION', 'ELIMINACION', 'NOTIFICACION', 'MODIFICACION_USUARIO', 'IMPORTACION_INICIADA', 'DETECCION_COMPLETADA', 'IMPORTACION_CONFIRMADA', 'IMPORTACION_CANCELADA', 'ERROR_PROCESAMIENTO'])), name='ck_log_tipo_evento_valido'),
        ),
    ]
