# Generated by Django 6.1 on 2026-09-10 23:14

from django.conf import settings
from django.db import migrations, models


def normalizar_eventos_historicos(apps, schema_editor):
    """Conserva los logs de versiones previas antes de acotar el enum."""

    LogActividad = apps.get_model("auditoria", "LogActividad")
    LogActividad.objects.filter(
        tipo_evento__in=["DETECCION_COMPLETADA", "ERROR_PROCESAMIENTO"]
    ).update(tipo_evento="CARGA")


def no_revertir_eventos(apps, schema_editor):
    """La reversión no puede deducir el valor técnico original."""


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_remove_logactividad_ck_log_tipo_evento_valido_and_more'),
        ('estudios', '0005_importacionestudio_ck_importacion_confirmada_con_formato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logactividad',
            name='ck_log_tipo_evento_valido',
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='tipo_evento',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('CARGA', 'Carga'), ('PUBLICACION', 'Publicación'), ('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('REVOCACION', 'Revocación'), ('CORRECCION', 'Corrección'), ('ELIMINACION', 'Eliminación'), ('NOTIFICACION', 'Notificación'), ('MODIFICACION_USUARIO', 'Modificación de usuario'), ('IMPORTACION_INICIADA', 'Importación iniciada'), ('IMPORTACION_CONFIRMADA', 'Importación confirmada'), ('IMPORTACION_CANCELADA', 'Importación cancelada')], max_length=30),
        ),
        migrations.RunPython(normalizar_eventos_historicos, no_revertir_eventos),
        migrations.AddConstraint(
            model_name='logactividad',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['INICIO_SESION', 'CARGA', 'PUBLICACION', 'VISUALIZACION', 'DESCARGA', 'REVOCACION', 'CORRECCION', 'ELIMINACION', 'NOTIFICACION', 'MODIFICACION_USUARIO', 'IMPORTACION_INICIADA', 'IMPORTACION_CONFIRMADA', 'IMPORTACION_CANCELADA'])), name='ck_log_tipo_evento_valido'),
        ),
    ]
